# Generated by Selenium IDE
# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestFluxoCompra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_compra_por_banner(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.find_element(By.ID, "perfil-hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("manuela.hadassa.daluz@gmaspst.com")
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("manuela@123")
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    # Preenchendo campo de senha novamente pois ao aparecer o captcha a senha preenchida foi apagada
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("manuela@123")
    # sleep pra resolver captcha
    time.sleep(10)
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    # Banner páscoa
    self.driver.find_element(By.CSS_SELECTOR, "img[alt='Páscoa']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[name='addressButton']").click()
    self.driver.find_element(By.CSS_SELECTOR, "div[class='apply-button']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item").click()
    self.driver.find_element(By.ID, "ContentSite_divBtBuy").click()
    self.driver.find_element(By.ID, "btConfirmShippingData").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "ContentSite_divBtBuy").click()
    self.driver.find_element(By.ID, "ContentSite_Basketcontrol1_rptBasket_imbFinalize_0").click()
    self.driver.find_element(By.ID, "txtDsDestinationName").click()
    self.driver.find_element(By.ID, "txtDsDestinationName").send_keys("Bruna Costa")
    self.driver.find_element(By.ID, "txtPhone").click()
    self.driver.find_element(By.ID, "txtPhone").send_keys("11111111111")
    self.driver.find_element(By.ID, "ContentSite_rptDeliveryAddress_rbtFgPersonalAddress_0_0_0").click()
    self.driver.find_element(By.ID, "txtDsNumber").click()
    self.driver.find_element(By.ID, "txtDsNumber").send_keys("123")
    self.driver.find_element(By.ID, "btnContinue").click()