# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestLoginNegativo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login_negativo(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.find_element(By.ID, "perfil-hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("manuela.hadassa.daluz@gmaspst.com")
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("manuela@")
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    # sleep pra resolver captcha
    time.sleep(60)
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()